-- NOMES DOS MEDICAMENTOS QUE ESTÃO VENCIDOS
-- (CONSULTA NORMAL)

SELECT M.NOME_MEDICAMENTO
FROM MEDICAMENTO M
WHERE M.VALIDADE_MEDICAMENTO < TO_DATE('2022/10/22','YYYY/MM/DD')

-- Projetar a quantidade de médicos por hospital 
--(GROUP BY, COUNT, INNER JOIN)

SELECT H.NOME_HOSPITAL, COUNT(M.CPF_MEDICO)
FROM MEDICO M INNER JOIN
	HOSPITAL H ON M.CNES_MEDICO = H.CNES_HOSPITAL
GROUP BY H.NOME_HOSPITAL

--Projetar a quantidade de médicos por hospital, se o hospital tem mais que 2 médicos 
--(GROUP BY, HAVING, COUNT, INNER JOIN)

SELECT H.NOME_HOSPITAL, COUNT(M.CPF_MEDICO)
FROM MEDICO M INNER JOIN
	HOSPITAL H ON M.CNES_MEDICO = H.CNES_HOSPITAL
GROUP BY H.NOME_HOSPITAL
HAVING COUNT(*) > 2

-- Projetar o nome dos pacientes que receberam alguma prescrição 
--(SUBCONSULTA DO TIPO TABELA E SEMI JOIN)

SELECT NOME_PACIENTE
FROM PACIENTE PA
WHERE PA.CPF_PACIENTE IN
(SELECT CPF_PAC_PRESCREVE FROM PRESCREVE)


-- Projetar os nomes de todos os atendentes e respectivos pacientes atendidos por eles que sejam do sexo feminimo
--(INNER JOIN)

SELECT P.NOME_PACIENTE, A.NOME_ATENDENTE
FROM PACIENTE P INNER JOIN ATENDENTE A
ON P.CPF_PACIENTE_ATENDENTE = A.CPF_ATENDENTE
WHERE P.SEXO = 'F'

-- Projetar o nome de todos os atendentes com idade superior a 45 anos e seus respectivos pacientes atendidos, quando houver 
--(LEFT OUTER JOIN)

SELECT A.NOME_ATENDENTE, P.NOME_PACIENTE
FROM ATENDENTE A LEFT OUTER JOIN
	PACIENTE P ON A.CPF_ATENDENTE = P.CPF_PACIENTE_ATENDENTE
WHERE A.DT_NASC_ATENDENTE < TO_DATE('1980/12/31','YYYY/MM/DD')

-- Projetar o nome de todos os atendentes com idade superior a 45 anos e seus respectivos pacientes atendidos, quando houver 
--(RIGHT OUTER JOIN)

SELECT A.NOME_ATENDENTE, P.NOME_PACIENTE
FROM PACIENTE P RIGHT OUTER JOIN
    ATENDENTE A ON A.CPF_ATENDENTE = P.CPF_PACIENTE_ATENDENTE
WHERE A.DT_NASC_ATENDENTE < TO_DATE('1980/12/31','YYYY/MM/DD')

-- Projetar os nomes de todos os enfermeiros que atuam na mesma categoria de um enfermeiro com CPF específico, e é mais velho que este
-- (SUBCONSULTA DO TIPO ESCALAR);

SELECT NOME_ENFERMEIRO
FROM ENFERMEIRO E
WHERE E.CATEGORIA =
	(SELECT CATEGORIA
	FROM ENFERMEIRO
	WHERE CPF_ENFERMEIRO = '28859793211')
	AND E.DT_NASC_ENFERMEIRO <
	(SELECT DT_NASC_ENFERMEIRO
	FROM ENFERMEIRO
    WHERE CPF_ENFERMEIRO = '28859793211')


-- Projetar o nome de todos os médicos que já foram gerentes do hospital e suas respectivas especialidades
-- (SUBCONSULTA DO TIPO TABELA E SEMI JOIN)

SELECT M.NOME_MEDICO, M.ESPECIALIDADE
FROM MEDICO M
WHERE M.CPF_MEDICO IN
	(SELECT *
	FROM GERENCIA G)

-- Projetar o nome dos médicos que atenderam mais pacientes do que a média 
-- (SUBCONSULTA DO TIPO ESCALAR)

SELECT M.NOME_MEDICO
FROM MEDICO M INNER JOIN 
(SELECT C.CPF_MED, COUNT(C.CPF_PAC)
    FROM CONSULTA C
    GROUP BY C.CPF_MED
    HAVING Count(*) > (SELECT AVG(QTD)
    	FROM (SELECT C.CPF_MED,COUNT(C.CPF_PAC) AS QTD
        	FROM CONSULTA C 
			GROUP  BY C.CPF_MED)))
ON M.CPF_MEDICO = CPF_MED 

-- O ramal dos atendentes que tem pacientes agendados 
--(SEMI JOIN COM IN)

SELECT A.RAMAL 
FROM ATENDENTE A
WHERE A.CPF_ATENDENTE IN
    (SELECT P.CPF_PACIENTE_ATENDENTE
     FROM PACIENTE P
     WHERE P.CPF_PACIENTE_ATENDENTE IS NOT NULL);

-- O ramal dos atendentes que NÃO tem pacientes agendados 
--(ANTI JOIN COM IN)

SELECT A.RAMAL
FROM ATENDENTE A
WHERE A.CPF_ATENDENTE NOT IN
    (SELECT P.CPF_PACIENTE_ATENDENTE
     FROM PACIENTE P
     WHERE P.CPF_PACIENTE_ATENDENTE IS NOT NULL);

-- Projetar os nomes dos médicos que trabalham na mesma instituição e tem a mesma especialidade que o médico com o cpf 27719625196
--(SUBCONSULTA DO TIPO LINHA)

SELECT NOME_MEDICO
FROM MEDICO
WHERE  CPF_MEDICO != '27719625196' AND (CNES_MEDICO, ESPECIALIDADE) =
    (SELECT CNES_MEDICO, ESPECIALIDADE
    FROM MEDICO
    WHERE CPF_MEDICO = '27719625196');

--  Para cada médico projetar o seu nome e o nome dos médicos mais novos que ele
-- (AUTO JUNÇÃO)

SELECT M1.NOME_MEDICO, M2.NOME_MEDICO
FROM MEDICO M1 INNER JOIN 
    MEDICO M2 ON M1.DT_NASC_MEDICO < M2.DT_NASC_MEDICO

-- O ramal dos atendentes que tem pacientes agendados 
-- (SEMI JOIN COM EXISTS)

SELECT A.RAMAL
FROM ATENDENTE A
WHERE EXISTS
    (SELECT P.CPF_PACIENTE_ATENDENTE
     FROM PACIENTE P
     WHERE P.CPF_PACIENTE_ATENDENTE = A.CPF_ATENDENTE);

-- O ramal dos atendentes que NÃO tem pacientes agendados 
-- (ANTI JOIN COM NOT EXISTS)

SELECT A.RAMAL
FROM ATENDENTE A
WHERE NOT EXISTS
    (SELECT P.CPF_PACIENTE_ATENDENTE
     FROM PACIENTE P
     WHERE P.CPF_PACIENTE_ATENDENTE = A.CPF_ATENDENTE);

-- Projetar o nome de todos os funcionários (medicos, enfermeiros e atendentes)
-- (UNION)

SELECT NOME_ENFERMEIRO AS FUNCIONÁRIOS FROM ENFERMEIRO
UNION SELECT NOME_ATENDENTE FROM ATENDENTE
UNION SELECT NOME_MEDICO FROM MEDICO

-- Projetar o nome de todos que são médicos e pacientes ao mesmo tempo 
-- (INTERSECT)

SELECT NOME_MEDICO, CPF_MEDICO FROM MEDICO 
INTERSECT SELECT NOME_PACIENTE, CPF_PACIENTE FROM PACIENTE

-- Projeta o nome e o CPF dos médicos que são chefes de outros médicos:
-- (AUTO RELACIONAMENTO)

SELECT NOME_MEDICO, CPF_MEDICO FROM MEDICO 
WHERE CPF_MEDICO IN (SELECT CPF_MEDICO_CHEFE FROM MEDICO)