CREATE TABLE HOSPITAL(
    CNES_HOSPITAL VARCHAR (20) PRIMARY KEY,
    NOME_HOSPITAL VARCHAR(50),
    CEP VARCHAR(8),
    LOGRADOURO VARCHAR(100)
);


CREATE TABLE ATENDENTE (
    CPF_ATENDENTE VARCHAR (20) PRIMARY KEY,
    RAMAL VARCHAR(3),
    NOME_ATENDENTE VARCHAR(100),
    DT_NASC_ATENDENTE DATE,
    CNES_ATENDENTE VARCHAR (20) NOT NULL,
    CONSTRAINT ATEND_HOSP_FK FOREIGN KEY (CNES_ATENDENTE) REFERENCES HOSPITAL (CNES_HOSPITAL)
);



CREATE TABLE PACIENTE (
    CPF_PACIENTE VARCHAR (20) PRIMARY KEY,
    NOME_PACIENTE VARCHAR (50),
    DT_NASC_PACIENTE DATE,
    CPF_PACIENTE_ATENDENTE VARCHAR(20),
    DDD_1 VARCHAR(5),
    NUMERO_1 VARCHAR(10),
    DDD_2 VARCHAR(5),
    NUMERO_2 VARCHAR(10),
    SEXO VARCHAR(20),
    CONSTRAINT PAC_ATEND_FK FOREIGN KEY (CPF_PACIENTE_ATENDENTE) REFERENCES ATENDENTE (CPF_ATENDENTE)
);




CREATE TABLE MEDICAMENTO(
    LOTE_MEDICAMENTO VARCHAR(60) PRIMARY KEY,
    NOME_MEDICAMENTO VARCHAR(50),
    VALIDADE_MEDICAMENTO DATE
);




CREATE TABLE ENFERMEIRO(
    CPF_ENFERMEIRO VARCHAR(20) PRIMARY KEY,
    CATEGORIA VARCHAR(20),
    NOME_ENFERMEIRO VARCHAR(60),
    DT_NASC_ENFERMEIRO DATE,
    CNES_ENFERMEIRO VARCHAR (20) NOT NULL,
    CONSTRAINT ENF_HOSP_FK FOREIGN KEY (CNES_ENFERMEIRO) REFERENCES HOSPITAL(CNES_HOSPITAL)
);



CREATE TABLE MEDICO(
    CPF_MEDICO VARCHAR(20) PRIMARY KEY,
    NOME_MEDICO VARCHAR(100),
    DT_NASC_MEDICO DATE,
    ESPECIALIDADE VARCHAR(25),
    CPF_MEDICO_CHEFE VARCHAR(20),
    CNES_MEDICO VARCHAR (20) NOT NULL,
    CONSTRAINT CPF_CHEFE_FK FOREIGN KEY (CPF_MEDICO_CHEFE) REFERENCES MEDICO (CPF_MEDICO),
    CONSTRAINT MED_HOSP_FK FOREIGN KEY (CNES_MEDICO) REFERENCES HOSPITAL (CNES_HOSPITAL)
);



CREATE TABLE ESTOQUE (
    CNES_ESTOQUE VARCHAR (20),
    LOTE_ESTOQUE VARCHAR(60),
    NOME_DE_ESTOQUE VARCHAR(30),
    QNT_DE_REMEDIO INT DEFAULT 0,
    CONSTRAINT CHK_QNT_REMEDIO CHECK (QNT_DE_REMEDIO > -1),
    CONSTRAINT ESTOQUE_PK PRIMARY KEY (CNES_ESTOQUE, LOTE_ESTOQUE),
    CONSTRAINT EST_HOSP_FK FOREIGN KEY (CNES_ESTOQUE) REFERENCES HOSPITAL (CNES_HOSPITAL),
    CONSTRAINT EST_MED_FK FOREIGN KEY (LOTE_ESTOQUE) REFERENCES MEDICAMENTO (LOTE_MEDICAMENTO)
);


CREATE TABLE CONSULTA (
    CPF_MED VARCHAR (20),
    CPF_PAC VARCHAR (20),
    TIMESTAMP_CONSULTA TIMESTAMP,
    CONSTRAINT CONSULTA_PK PRIMARY KEY (CPF_MED, CPF_PAC, TIMESTAMP_CONSULTA),
    CONSTRAINT CONS_MED_FK FOREIGN KEY (CPF_MED) REFERENCES MEDICO(CPF_MEDICO),
    CONSTRAINT CONS_PAC_FK FOREIGN KEY (CPF_PAC) REFERENCES PACIENTE(CPF_PACIENTE)
);


CREATE TABLE MEDICA(
    LOTE_MEDICA VARCHAR(60),
    CPF_PAC_MEDICA VARCHAR(11),
    CPF_ENF VARCHAR(11),
    TIMESTAMP_MEDICA TIMESTAMP,
    CONSTRAINT MEDICA_PK PRIMARY KEY (LOTE_MEDICA, CPF_PAC_MEDICA, CPF_ENF, TIMESTAMP_MEDICA),
    CONSTRAINT MEDICA_MED_FK FOREIGN KEY (LOTE_MEDICA) REFERENCES MEDICAMENTO (LOTE_MEDICAMENTO),
    CONSTRAINT MEDICA_ENF_FK FOREIGN KEY (CPF_ENF) REFERENCES ENFERMEIRO (CPF_ENFERMEIRO),
    CONSTRAINT MEDICA_PAC_FK FOREIGN KEY (CPF_PAC_MEDICA) REFERENCES PACIENTE (CPF_PACIENTE)
);


CREATE TABLE PRESCREVE(
    CPF_MED_PRESCREVE VARCHAR(11),
    CPF_PAC_PRESCREVE VARCHAR(11),
    LOTE_PRESCREVE VARCHAR(60),
    TIMESTAMP_PRESCREVE TIMESTAMP,
    CONSTRAINT PRESCREVE_PK PRIMARY KEY (CPF_MED_PRESCREVE, CPF_PAC_PRESCREVE, TIMESTAMP_PRESCREVE, LOTE_PRESCREVE),
    CONSTRAINT PRESC_CONS_FK FOREIGN KEY (CPF_MED_PRESCREVE, CPF_PAC_PRESCREVE, TIMESTAMP_PRESCREVE) REFERENCES CONSULTA (CPF_MED, CPF_PAC, TIMESTAMP_CONSULTA),
    CONSTRAINT PRESC_MED_FK FOREIGN KEY (LOTE_PRESCREVE) REFERENCES MEDICAMENTO (LOTE_MEDICAMENTO)
);



CREATE TABLE GERENCIA(
	CPF_MEDICO_GERENCIA VARCHAR(11),
CONSTRAINT MED_GER_FK FOREIGN KEY (CPF_MEDICO_GERENCIA) REFERENCES MEDICO (CPF_MEDICO)
   );

